config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :houses, only: [:index]
  resources :cities, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class City < ApplicationRecord
  has_many :houses, class_name: 'House', dependent: :destroy
  has_many :energies, through: :houses
end

app/models/energy.rb
# == Schema Information
#
# Table name: energies
#
#  id                :bigint           not null, primary key
#  label             :integer
#  house_id          :integer
#  year              :integer
#  month             :integer
#  temperature       :decimal(10, )
#  daylight          :decimal(10, )
#  energy_production :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Energy < ApplicationRecord
  belongs_to :house, class_name: 'House'
  has_one :city, through: :house

  def self.dates
    distinct.pluck(:year, :month).map { |year, month| "#{year}-#{month}" }
  end
end

app/models/house.rb
# == Schema Information
#
# Table name: houses
#
#  id            :bigint           not null, primary key
#  firstname     :string(255)
#  lastname      :string(255)
#  city_id       :integer
#  num_of_people :integer
#  has_child     :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class House < ApplicationRecord
  belongs_to :city, class_name: 'City'
  has_many :energies, class_name: 'Energy', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    cities = City.select(:id, :name)
    @cities_data = CityChartService.call(cities)
    @dates = Energy.dates
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.eager_load(:city, :energies)
    @houses_data = HouseChartService.call(@houses)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cities/index.html.haml
%h1 市ごとのエネルギー生産量月推移
= line_chart @cities_data

%table
  %thead
    %tr
      %th name
      - @dates.each do |date|
        %th
          = date
  - @cities_data.each do |city_data|
    %tr
      %td
        = city_data[:name]
      - city_data[:data].values.each do |energy_production|
        %td
          = energy_production

app/views/houses/index.html.haml
%h1 家庭ごとのエネルギー生産量
= bar_chart @houses_data

%table
  %thead
    %tr
      %th id
      %th firstname
      %th lastname
      %th city
      %th num_of_people
      %th has_child
      %th energy_production
  - @houses.each do |house|
    %tr
      %td
        = house.id
      %td
        = house.firstname
      %td
        = house.lastname
      %td
        = house.city.name
      %td
        = house.num_of_people
      %td
        = house.has_child
      %td
        = house.energies.pluck(:energy_production).sum

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EnechangeCh3
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/static_pages/index.html.haml
%h1
  Enechange Challenge 3 - Web Application
%h2
  家庭のエネルギー生産量チャート

%ul
  %li
    = link_to '家庭ごとのエネルギー生産量', houses_path
  %li
    = link_to '市ごとの月別エネルギー生産量', cities_path